### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by ridwanediallo** [teckim/carbook-api#11]
## We are 4 members in this team:
:one: @teckim 
:two: @bigmosi 
:three: @ridwanediallo 
:four: @HanningtoneM 

[Link to the project](https://github.com/users/teckim/projects/2/views/1)

## Screenshot
![Screenshot from 2022-10-20 13-55-41](https://user-images.githubusercontent.com/89228743/196984547-5569b508-be9b-4216-9f54-ceb5a6e0a483.png)

**Comment by Meltrust** [comment]
Hi @ridwanediallo,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned✔️ 
- All tasks have points✔️ 
- Equal manual toil✔️ 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
